/* 
	contacto in table empleados
    cod dato movil
*/

CREATE DATABASE IF NOT EXISTS longaniza;

USE longaniza;

CREATE TABLE IF NOT EXISTS empleados (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    contacto VARCHAR(50) NOT NULL,
    dni INT NOT NULL,
	sueldo DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS productos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL,
	precio_unitario DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS raza (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS mascotas (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    raza INT NOT NULL,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS clientes_mascotas (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente INT NOT NULL,
    mascota INT NOT NULL
);

CREATE TABLE IF NOT EXISTS clientes (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dni INT NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    datos_ficales INT NOT NULL UNIQUE,
    apellido VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS datos_ficales (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tipo_iva VARCHAR(50) NOT NULL,
    procentaje DOUBLE NOT NULL,
    descuento INT NOT NULL
);

CREATE TABLE IF NOT EXISTS facturas_productos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    factura INT NOT NULL,
    producto INT NOT NULL,
    cantidad INT NOT NULL,
    precio_de_compra DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS facturas (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente INT NOT NULL,
    total DOUBLE NOT NULL,
    fecha DATE NOT NULL
);

SHOW TABLES;
